name: Validate
on:
    workflow_call:
    pull_request:
    push:
        branches:
            - develop

jobs:
    validate:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Run Checks
              run: bun check

            - name: Build
              run: bun run build

    validate-firefox-sources:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Build and create Firefox sources
              run: bun run zip:fox

            - name: Extract version
              run: |
                  VERSION=$(bun --print 'require("./package.json").version')
                  echo "VERSION=$VERSION" >> "$GITHUB_ENV"

            - name: Extract and validate sources
              run: |
                  cd .output
                  unzip -q chorus-$VERSION-sources.zip
                  cd chorus-$VERSION-sources
                  bun install --frozen-lockfile
                  bun run build:fox

            - name: Compare builds
              run: |
                  diff -r .output/firefox-mv3 .output/chorus-$VERSION-sources/.output/firefox-mv3
                  if [ $? -eq 0 ]; then
                      echo "✅ Firefox source validation passed - builds are identical"
                  else
                      echo "❌ Firefox source validation failed - builds differ"
                      exit 1
                  fi
